apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: messaging-service
  name: messaging-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: messaging-service
  strategy: { }
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: messaging-service
    spec:
      containers:
        - env:
            - name: BOT_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: BOT_TOKEN
                  name: messaging-service--env
            - name: SHARDED
              valueFrom:
                configMapKeyRef:
                  key: SHARDED
                  name: messaging-service--env
          image: messaging_service:latest
          imagePullPolicy: Never
          name: messaging-service
          ports:
            - containerPort: 5001
          resources: { }
      restartPolicy: Always
status: { }
