version: "3.9"
services:
  bot:
    env_file: .env
    image: "arcbot:latest"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - arcbot-data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  arcbot-data:
